version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    ports:
      - "80:80"
    environment:
      IDENTITY_SECRET: change_me_____k3uJYxJY1vSxg9ow2yRIqaHFfsqb4JjIzkYck8A2qK2887yUQtEHshAO428775q5
      PORT: 80
      DATABASE_URL: postgres://postgres:root@db:5432/postgres
      REDIS_URL: redis://redis:6379
      LLM_API_URL: http://llm-api:11434
    depends_on:
      - db
      - redis
      - llm-api
    restart: always

  llm-api:
    image: ollama/ollama:0.1.27
    ports:
      - "11434:11434"
    volumes:
      - llm_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all
    restart: always

volumes:
  postgres_data:
  llm_data: